# Generated by Django 3.2.10 on 2022-02-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_wise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='theory_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='theoryTopic')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='course_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('course_title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('dept', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.department_wise')),
            ],
        ),
    ]
