# Generated by Django 3.2.10 on 2022-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory_topic',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
