# Generated by Django 3.2.10 on 2022-02-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_theory_topic_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_blog',
            name='dept',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.department_wise'),
        ),
    ]
