# Generated by Django 3.2.10 on 2022-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_course_blog_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_blog',
            name='dept',
        ),
        migrations.DeleteModel(
            name='department_wise',
        ),
    ]
