# Generated by Django 3.2.10 on 2022-01-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('Rpassword', models.CharField(max_length=20)),
                ('website', models.URLField(max_length=100)),
                ('state', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=30)),
                ('postalcode', models.IntegerField()),
                ('file_upload', models.FileField(upload_to='upload')),
            ],
        ),
    ]
