# Generated by Django 3.2.10 on 2022-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicpython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='basicPython')),
            ],
        ),
    ]
