# Generated by Django 3.2.10 on 2022-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_basic_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_c',
            name='image',
            field=models.ImageField(upload_to='Cimage'),
        ),
        migrations.AlterField(
            model_name='basicpython',
            name='img',
            field=models.ImageField(upload_to='pyhtonimg'),
        ),
    ]
