# Generated by Django 3.2.10 on 2022-01-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220122_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basicpython',
        ),
    ]
