# Generated by Django 3.2.10 on 2022-01-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_basicpython_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basic_c',
        ),
        migrations.DeleteModel(
            name='basicPython',
        ),
    ]
