# Generated by Django 3.2.10 on 2022-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cprog'),
    ]

    operations = [
        migrations.CreateModel(
            name='websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='websiteimg')),
                ('site', models.URLField()),
                ('price', models.IntegerField()),
                ('facebook', models.URLField(max_length=400)),
                ('twitter', models.URLField(max_length=400)),
                ('mail', models.EmailField(max_length=400)),
            ],
        ),
    ]
