# Generated by Django 3.2.10 on 2022-01-23 08:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_websites'),
    ]

    operations = [
        migrations.CreateModel(
            name='code_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='code')),
                ('code', tinymce.models.HTMLField()),
            ],
        ),
    ]
